### ISSUE TITLE
Built in LSP support

### ISSUE THREAD

**Issue by jacksonludwig** [doums/barowLSP#2]
First, thanks for your work and great plugin.
I am just wondering, would you consider adding support for builtin LSP to this statusline plugin? I am having issues making my own module to do it.

**Comment by doums** [comment]
Hi, you're welcome,

It's in the plan, but I don't know when I will add a support for it as nvim 0.5 is not released yet, and we don't know when it will be.
And I don't use 0.5 myself, but stable release.
